app/main/models.py
from app import db
from sqlalchemy.sql import text
from flask import abort


class DB:
    @classmethod
    def getCommunity(cls, id):
        cmd = """
            SELECT id, name, latitude, longitude, northing, easting
            FROM new_communities
            WHERE id=:id;
            """
        result = db.engine.execute(text(cmd), id=id).fetchone()
        return result or abort(500)

    @classmethod
    def getCommunities(cls):
        cmd = """
            SELECT id, name
            FROM new_communities
            ORDER BY name ASC;
            """
        result = db.engine.execute(text(cmd), id=id).fetchall()
        return result or abort(500)

    @classmethod
    def getDatasets(cls):
        cmd = """
            SELECT DISTINCT ON (
                doc->'datatype',
                doc->'resolution',
                doc->'modelname',
                doc->'scenario'
            )
                doc->'datatype' AS datatype,
                doc->'resolution' AS resolution,
                doc->'modelname' AS modelname,
                doc->'scenario' AS scenario
            FROM new_communities c,
                jsonb_array_elements(c.data)
                WITH ORDINALITY t1(doc, rn)
            ORDER BY datatype ASC, modelname ASC, scenario ASC;
            """
        result = db.engine.execute(text(cmd)).fetchall()
        return result or abort(500)

    @classmethod
    def getTemps(cls, start, end, community_id, modelname, scenario):
        years = [str(x) for x in range(int(start), int(end)+1)]
        cmd = """
            WITH x AS (
                SELECT name, jsonb_array_elements(data) AS data
                FROM new_communities
                WHERE id=:community_id)
            SELECT d.key AS year, d.value AS temperatures
            FROM x, jsonb_each(data) d
            WHERE data->>'modelname'=:modelname
            AND data->>'scenario'=:scenario
            AND d.key IN :years;
            """
        result = db.engine.execute(text(cmd),
                                   community_id=community_id,
                                   modelname=modelname,
                                   scenario=scenario,
                                   years=tuple(years)).fetchall()
        return result or abort(500)

app/main/forms.py
from flask_wtf import Form
from wtforms import IntegerField, SelectField
from wtforms.validators import NumberRange, Required


class AKIYearField(IntegerField):
    def pre_validate(self, form):
        if form.data['dataset'] == 'CRU,TS31':
            self.validators = [NumberRange(min=1901, max=2009), Required()]
        else:
            self.validators = [NumberRange(min=2001, max=2099), Required()]


class AKIForm(Form):
    community = SelectField(coerce=int,
                            validators=[Required(message='Please select a community')])
    dataset = SelectField(validators=[Required(message='Please select a dataset')])
    minyear = AKIYearField('minyear')
    maxyear = AKIYearField('maxyear')

app/main/__init__.py
from flask import Blueprint


main = Blueprint('main', __name__, template_folder='templates')


from . import views

app/main/views.py
from flask import session, render_template, request, redirect, url_for

from . import main
from .forms import AKIForm
from .utils import getTemps, avg_air_temp, ann_air_indices, \
    avg_air_indices, des_air_indices, communitiesSelect, datasetsSelect
from .models import DB


@main.route('/', methods=['GET', 'POST'])
def index():
    form = AKIForm()
    form.community.choices = communitiesSelect()
    form.dataset.choices = datasetsSelect()

    if form.validate_on_submit():
        session['community'] = request.form['community']
        session['minyear'] = request.form['minyear']
        session['maxyear'] = request.form['maxyear']
        if session['minyear'] > session['maxyear']:
            session['maxyear'] = session['minyear']

        session['datasets'] = request.form['dataset']
        return redirect(url_for('main.index'))

    session['community_data'] = None
    session['avg_temp'] = None
    session['avg_indices'] = None
    session['des_indices'] = None

    if 'community' in session:
        community_id = session['community']
        if all(key in session for key in ('minyear', 'maxyear', 'datasets')):
            community = DB.getCommunity(community_id)

            session['community_data'] = {
                'id': community_id,
                'name': community['name'],
                'latitude': round(community['latitude'], 5),
                'longitude': round(community['longitude'], 5),
            }

            session['ds_name'] = session['datasets'].split(',')

            temps_arr = getTemps(session)

            session['avg_temp'] = avg_air_temp(temps_arr)
            indices = ann_air_indices(temps_arr)
            session['avg_indices'] = avg_air_indices(indices)
            session['des_indices'] = des_air_indices(indices)

    return render_template('main/index.html', form=form)


@main.route('/datatypes')
def datatypes():
    return render_template('main/datatypes.html')


@main.route('/reset')
def reset():
    session.clear()
    return redirect(url_for('main.index'))


@main.route('/details')
def details():
    temps = getTemps({'datasets': request.args.get('datasets', ''),
                     'minyear': request.args.get('minyear', ''),
                     'maxyear': request.args.get('maxyear', ''),
                     'community_data': {'id': request.args.get('community_id', '')}
    })
    return render_template('main/details.html',
                           lat=request.args.get('lat', ''),
                           lon=request.args.get('lon', ''),
                           community_name=request.args.get('name', ''),
                           temps=temps)


@main.route('/save')
def save():
    if 'save' in session:
        i = str(len(session['save']))
        save = session['save']
    else:
        save = dict()
        i = '0'

    save[i] = {
        'datasets': session['datasets'],
        'ds_name': session['ds_name'],
        'community_data': session['community_data'],
        'minyear': session['minyear'],
        'maxyear': session['maxyear'],
        'avg_temp': session['avg_temp'],
        'avg_indices': session['avg_indices'],
        'des_indices': session['des_indices'],
    }

    session.clear()
    session['save'] = save
    return redirect(url_for('main.index'))


@main.route('/delete')
def delete():
    record = request.args.get('record', '')
    session['save'].pop(record)
    return redirect(url_for('main.index'))

app/main/templates/main/_formhelpers.html
{% macro render_field(field) %}
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
    <div class="alert alert-danger">
        <ul>
        {% for error in field.errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    </div>
  {% endif %}
{% endmacro %}

app/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ config['TITLE'] }}</title>
        <link href="/static/css/bootstrap-readable.min.css" rel="stylesheet">
        <link href="/static/css/akindices.css" rel="stylesheet">
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
    <script type=text/javascript>
        var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    <div class="container" style="max-width:90%">
        <div class="page-header">
            <h1>{{ config['TITLE'] }}<br><small>alaska climate data</small></h1>
        </div>
        {% block content %}{% endblock %}
        <hr>

        <div id="footer">
            <p class="text-muted credit">
                <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a> This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.
                <br>
                <small>Created by <a href="mailto:matthew@akdillon.net">Matthew Dillon</a>, {{ config['COPYRIGHT_YEAR'] }}.</small>
            </p>
        </div>
    </div>
    </body>
</html>

app/main/templates/main/datatypes.html
{% extends "main/base.html" %}
{% block content %}

<h3>Model Details</h3>
<dl class="dl-horizontal">
  <dt>CCCMA CGCM 3.1</dt>
  <dd>
    Canadian Centre for Climate Modeling and Analysis &ndash; General Circulation Model version 3.1 - t47
  </dd>
  <dt>MPI ECHAM 5</dt>
  <dd>
    Max Planck Institute for Meteorology &ndash; European Centre Hamburg Model 5
  </dd>
  <dt>GFDL CM 2.1</dt>
  <dd>
    Geophysical Fluid Dynamics Laboratory &ndash; Coupled Climate Model 2.1
  </dd>
  <dt>UKMO HADCM 3.0</dt>
  <dd>
    UK Met Office - Hadley Centre &ndash; Coupled Model 3.0
  </dd>
  <dt>MIROC 3.2</dt>
  <dd>
    Center for Climate System Research &ndash; Model for Interdisciplinary Research on Climate (medium resolution)
  </dd>
  <dt>5 Model Average</dt>
  <dd>
    A composite of the five models listed above
  </dd>
</dl>

<h3>Emission Scenario Details (from <a href="https://uaf-snap.org/methods-overview/model-selection/">SNAP</a>)</h3>
<dl class="dl-horizontal">
  <dt>Scenario A1B</dt>
  <dd>
    <ul>
      <li>Rapid economic growth</li>
      <li>A global population that reaches 9 billion in 2050 and then gradually declines</li>
      <li>The quick spread of new and efficient technologies</li>
      <li>A convergent world - income and way of life converge between regions</li>
      <li>Extensive social and cultural interactions worldwide</li>
      <li>A balanced emphasis on all energy sources</li>
    </ul>
  </dd>
  <dt>Scenario B1</dt>
  <dd>
    <ul>
      <li>Rapid economic growth as in A1B, but with rapid changes towards a service and information economy</li>
      <li>Population rising to 9 billion in 2050 and then declining as in A1</li>
      <li>Reductions in material intensity and the introduction of clean and resource efficient technologies</li>
      <li>An emphasis on global solutions to economic, social and environmental stability</li>
    </ul>
  </dd>
  <dt>Scenario A2</dt>
  <dd>
    <ul>
      <li>A world of independently operating, self-reliant nations</li>
      <li>Continuously increasing population</li>
      <li>Regionally oriented economic development</li>
      <li>Slower and more fragmented technological changes and improvements to per capita income</li>
    </ul>
  </dd>
</dl>

{% endblock %}

app/main/templates/main/details.html
{% extends "main/base.html" %}
{% block content %}

<link rel="stylesheet" href="https://npmcdn.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
<script src="https://npmcdn.com/leaflet@1.0.0-rc.3/dist/leaflet.js"></script>

<h2>{{ community_name }}</h4>

<div id="map" style="width: 500px; height: 300px"></div>
<br>

<h3>Monthly Temperatures</h3>
<div class="table-responsive">
    <table class="table table-hover table-condensed table-bordered">
        <thead>
            <tr>
                <th class="col-md-1">Year<br>&nbsp;</th>
                <th class="col-md-1">January<br>&deg;C</th>
                <th class="col-md-1">February<br>&deg;C</th>
                <th class="col-md-1">March<br>&deg;C</th>
                <th class="col-md-1">April<br>&deg;C</th>
                <th class="col-md-1">May<br>&deg;C</th>
                <th class="col-md-1">June<br>&deg;C</th>
                <th class="col-md-1">July<br>&deg;C</th>
                <th class="col-md-1">August<br>&deg;C</th>
                <th class="col-md-1">September<br>&deg;C</th>
                <th class="col-md-1">October<br>&deg;C</th>
                <th class="col-md-1">November<br>&deg;C</th>
                <th class="col-md-1">December<br>&deg;C</th>
            </tr>
        </thead>
        <tbody>
           {% for temp in temps %}
                <tr>
                    <td>{{ temp[0] }}</td>
                    <td>{{ temp[1][0] }}</td>
                    <td>{{ temp[1][1] }}</td>
                    <td>{{ temp[1][2] }}</td>
                    <td>{{ temp[1][3] }}</td>
                    <td>{{ temp[1][4] }}</td>
                    <td>{{ temp[1][5] }}</td>
                    <td>{{ temp[1][6] }}</td>
                    <td>{{ temp[1][7] }}</td>
                    <td>{{ temp[1][8] }}</td>
                    <td>{{ temp[1][9] }}</td>
                    <td>{{ temp[1][10] }}</td>
                    <td>{{ temp[1][11] }}</td>
                </tr>
       {% endfor %}
   </tbody>
</table>

<script>
var map = L.map('map').setView([{{ lat }}, {{ lon }}], 5);
L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: '{{ community_name }}, AK'
}).addTo(map);
var marker_1 = L.marker([{{ lat }}, {{ lon }}]);
marker_1.bindPopup("{{ community_name }}, AK<br>{{ lat }}&deg; N, {{ lon }}&deg; W");
map.addLayer(marker_1)
</script>

{% endblock %}

app/main/templates/main/index.html
{% extends "main/base.html" %}
{% from "main/_formhelpers.html" import render_field %}
{% block content %}

<p class="lead" align="justify">
    Air temperature data from over 400 communities, reduced to relevant engineering parameters
    (<a href="#info">Additional info</a>)
</p>

<h3>Search</h3>

<form action="" method="post" role="form">
    {{ form.csrf_token }}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-4">
                <label for="communityinput">Community</label>
                {{ render_field(form.community, class='form-control', id='communityinput') }}
            </div>
            <div class="form-group col-md-4">
                <label for="modelinput">Dataset</label>
                {{ render_field(form.dataset, class='form-control', id='modelinput') }}
                    <small>Historical (1901-2009) or Projection (2001-2099)<br>
                    <a href="{{ url_for('main.datatypes') }}" target="_blank">
                    Learn more about the models and scenarios
                </a></small>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-4">
                <label for="minyearinput">Start Year</label>
                {{ render_field(form.minyear, class='form-control', id='minyearinput') }}
            </div>

            <div class="form-group col-md-4">
                <label for="maxyearinput">End Year</label>
                {{ render_field(form.maxyear, class='form-control', id='maxyearinput') }}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-4">
                <input type="submit" name="submit" class="btn btn-primary form-control"
                       value="Get Temperatures" />
            </div>
            <div class="form-group col-md-4">
                <input type="button" name="reset" class="btn btn-danger form-control"
                       onclick="window.location.href='{{ url_for('main.reset') }}'"
                       value="Clear All Data" />
            </div>
        </div>
    </div>
</form>

<h3>Results</h3>
        <div class="table-responsive">
            <table class="table table-hover table-condensed table-bordered">
                <thead>
                    <tr>
                        <th>Community<br>&nbsp;</th>
                        <th>Years<br>&nbsp;</th>
                        <th>T<sub>avg</sub><br>&deg;C</th>
                        <th>ATI<br>&deg;C-days</th>
                        <th>AFI<br>&deg;C-days</th>
                        <th>DTI<br>&deg;C-days</th>
                        <th>DFI<br>&deg;C-days</th>
                        <th>Type<br>&nbsp;</th>
                        <th width="50px">Add/<br>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="active">
                        <td colspan="9" align="center">
                            Current Search
                        </td>
                    </tr>
                    {% if session['avg_temp'] %}
                    <tr>
                        <td><a href="{{ url_for('main.details', lat=session['community_data']['latitude'],
                                        lon=session['community_data']['longitude'],
                                        name=session['community_data']['name'],
                                        datasets=session['datasets'],
                                        community_id=session['community_data']['id'],
                                        minyear=session['minyear'],
                                        maxyear=session['maxyear']) }}"
                                        target="_blank">
                                        {{ session['community_data']['name'] }}<br>
                            <small>{{ session['community_data']['latitude'] }}&deg; N,
                            {{ session['community_data']['longitude'] }}&deg; W</small></a></td>
                        <td>{{ session['minyear'] }} - {{ session['maxyear'] }}</td>
                        <td>{{ session['avg_temp']|round(1) }}</td>
                        <td>{{ session['avg_indices'][0] }}</td>
                        <td>{{ session['avg_indices'][1] }}</td>
                        <td>{{ session['des_indices'][0] }}</td>
                        <td>{{ session['des_indices'][1] }}</td>
                        <td>{{ session['ds_name'][0] }} ({{ session['ds_name'][1] }})</td>
                        <td><button type="button" class="btn btn-success btn-sm"
                                    onclick="window.location.href='{{ url_for('main.save') }}'"
                                    title="Click to save this search">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                            </button></td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="9" align="center">
                            [no data]
                        </td>
                    </tr>
                    {% endif %}
                    <tr class="active">
                        <td colspan="9" align="center">
                            Saved Searches
                        </td>
                    </tr>
                    {% if session.save %}
                    {% for key, value in session.save|dictsort %}
                    <tr>
                        <td><a href="{{ url_for('main.details', lat=value['community_data']['latitude'],
                                        lon=value['community_data']['longitude'],
                                        name=value['community_data']['name'],
                                        datasets=value['datasets'],
                                        community_id=value['community_data']['id'],
                                        minyear=value['minyear'],
                                        maxyear=value['maxyear']) }}"
                                        target="_blank">
                                        {{ value['community_data']['name'] }}<br>
                            <small>{{ value['community_data']['latitude'] }}&deg; N,
                            {{ value['community_data']['longitude'] }}&deg; W</small></a></td>
                        <td>{{ value['minyear'] }} - {{ value['maxyear'] }}</td>
                        <td>{{ value['avg_temp']|round(1) }}</td>
                        <td>{{ value['avg_indices'][0] }}</td>
                        <td>{{ value['avg_indices'][1] }}</td>
                        <td>{{ value['des_indices'][0] }}</td>
                        <td>{{ value['des_indices'][1] }}</td>
                        <td>{{ value['ds_name'][0] }} ({{ value['ds_name'][1] }})</td>
                        <td><button type="button" class="btn btn-danger btn-sm"
                            onclick="window.location.href='{{ url_for('main.delete', record=key) }}'"
                            title="Click to delete this search">
                            <span class="glyphicon glyphicon-trash"></span></button></td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="9" align="center">
                            [no data]
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        <strong>
        NOTE: The parameters calculated by AKIndices are based on average monthly temperatures,
        not average daily temperatures. As well, derived data is provided without any rounding or
        consideration for significant digits, allowing the user to decide what is appropriate for
        their analysis.
        </strong>
        </div>

<div align="justify">
<a name="info"></a>
<h3>Info</h3>
<dl class="dl-horizontal">
  <dt>What</dt>
  <dd>AKIndices provides basic engineering climate parameters that are commonly used for engineering and
      site-development purposes. These parameters include:
        <ul>
            <li><strong>T<sub>avg</sub>:</strong> The average (arithmetic mean) air temperature, based on all of
                the monthly air temperatures for the specified range of years.
            </li>
            <li><strong>ATI:</strong> The average (arithmetic mean) annual thawing index. The thawing index is the
                total number of degree-days above the freezing point. The number displayed by AKIndices is the
                average of the annual indices for the specified range of years.
            </li>
            <li><strong>AFI:</strong> The average (arithmetic mean) annual freezing index. The freezing index is the
                total number of degree-days below the freezing point. The number displayed by AKIndices is the
                average of the annual indices for the specified range of years.
            </li>
            <li><strong>DTI:</strong> The design thawing index. The number displayed by AKIndices is the
                arithmetic mean of the three warmest thawing indices for the specified range of years. If less
                than three years are displayed, the DTI is listed as 'None.' Typically, the DTI is calculated
                over a 30-year or 10-year time span.
            </li>
            <li><strong>DFI:</strong> The design freezing index. The number displayed by AKIndices is the
                arithmetic mean of the three coolest freezing indices for the specified range of years. If less
                than three years are displayed, the DFI is listed as 'None.' Typically, the DFI is calculated
                over a 30-year or 10-year time span.
            </li>
        </ul>
  </dd>
  <dt>Why</dt>
  <dd>AKIndices provides quick and simple access to the massive amounts of data released by the SNAP
      group. It does not aim to replace, modify, or build on SNAP's work, but rather provide an alternative
      means for users to explore and understand the data.</dd>
  <dt>How</dt>
  <dd>AKIndices is built with <a href="https://www.python.org" target="_blank">python</a>. Check out
      <a href="https://github.com/thermokarst/AKExtract" target="_blank">AKExtract</a> and
      <a href="https://github.com/thermokarst/AKIndices" target="_blank">AKIndices</a> on GitHub for more info
      on how to install on your own machine, fork the project, or submit
      <a href="https://github.com/thermokarst/AKIndices/issues" target="_blank">bug reports.</a>
      In a nutshell, AKExtract takes a list of communities and their coordinates, as well as SNAP datasets,
      and extracts the air temperature data from the data point closest to a community's location. AKIndices
      is the front-end for interacting with that extracted data.
  </dd>
  <dt>Who</dt>
  <dd>This project is the work of <a href="mailto:matthew@akdillon.net">Matthew Dillon.</a>
      While this project would not exist without <a href="https://uaf-snap.org/" target="_blank">SNAP</a>,
      AKIndices is <em>not endorsed or supported by SNAP in any way.</em> Before utilizing the derived data
      from AKIndices make sure to take a look at SNAP's page to learn about the science
      and the methods behind their products.<br>
  </dd>
</dl>
<h4>This product is provided as-is, with no warranty express or implied. Use at your own risk.</h4>
<h4>Commercial use disclaimer: It is the sole responsibility of the user to execute any agreements
    with SNAP <a href="https://uaf-snap.org/contact/" target="_blank">regarding commercial
    use</a> of the SNAP data (potentially including the derived products found on this page).</h4>
<h4>Question? Comment? Find a problem? <a href="mailto:matthew@akdillon.net">Email me</a>
    or <a href="https://github.com/thermokarst/AKIndices/issues" target="_blank">submit a bug report!</a></h4>
</div>

{% endblock %}